# Generated by Django 4.1.4 on 2023-01-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empno', models.IntegerField(max_length=5)),
                ('Deptno', models.IntegerField(max_length=5)),
                ('Name', models.CharField(max_length=100)),
                ('Salary', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('SNO', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(max_length=2)),
                ('Email', models.CharField(max_length=100)),
                ('Marks', models.IntegerField(max_length=3)),
            ],
        ),
    ]
